# Basic

In [1]:
import numpy as np
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [2]:
a.shape  # 两个维度的大小

(3, 5)

In [3]:
a.ndim  # 维数

2

In [4]:
a.dtype.name    # 数据类型名称

'int64'

In [5]:
a.itemsize   # 列表每一项的字节大小

8

In [6]:
a.size   # 列表大小

15

In [7]:
type(a)    # 变量类型

numpy.ndarray

In [8]:
b = np.array([6, 7, 8])

In [9]:
b

array([6, 7, 8])

In [10]:
type(b)

numpy.ndarray

# Array creation

In [11]:
a = np.array([2, 3, 4])

In [12]:
a

array([2, 3, 4])

In [13]:
a.dtype

dtype('int64')

In [14]:
b = np.array([1.2, 3.5, 5.1])

In [15]:
b.dtype

dtype('float64')

In [16]:
b = np.array([(1.5, 2, 3), (4, 5, 6)])

In [17]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [18]:
c = np.array([[1, 2], [3, 4]], dtype=complex)

In [19]:
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [20]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
np.ones((2, 3, 4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [22]:
np.empty((2, 3)) 

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

empty creates an array whose initial content is random

In [23]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [24]:
np.arange(0, 2, 0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [25]:
from numpy import pi
np.linspace(0, 2, 9) 
x = np.linspace(0, 2 * pi, 100) 
f = np.sin(x)

In [26]:
f

array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -