# Basic

In [1]:
import numpy as np
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [2]:
a.shape  # 两个维度的大小

(3, 5)

In [3]:
a.ndim  # 维数

2

In [4]:
a.dtype.name    # 数据类型名称

'int64'

In [5]:
a.itemsize   # 列表每一项的字节大小

8

In [6]:
a.size   # 列表大小

15

In [7]:
type(a)    # 变量类型

numpy.ndarray

In [8]:
b = np.array([6, 7, 8])

In [9]:
b

array([6, 7, 8])

In [10]:
type(b)

numpy.ndarray

# Array creation

In [11]:
a = np.array([2, 3, 4])

In [12]:
a

array([2, 3, 4])

In [13]:
a.dtype

dtype('int64')

In [14]:
b = np.array([1.2, 3.5, 5.1])

In [15]:
b.dtype

dtype('float64')

In [16]:
b = np.array([(1.5, 2, 3), (4, 5, 6)])

In [17]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [18]:
c = np.array([[1, 2], [3, 4]], dtype=complex)

In [19]:
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [20]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
np.ones((2, 3, 4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [22]:
np.empty((2, 3)) 

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

empty creates an array whose initial content is random

In [23]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [24]:
np.arange(0, 2, 0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [25]:
from numpy import pi
np.linspace(0, 2, 9) 
x = np.linspace(0, 2 * pi, 100) 
f = np.sin(x)

In [26]:
f

array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -

# printing array

In [27]:
a = np.arange(6)                    # 1d array
print(a)

[0 1 2 3 4 5]


In [28]:
b = np.arange(12).reshape(4, 3)     # 2d array
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [29]:
c = np.arange(24).reshape(2, 3, 4)  # 3d array
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [30]:
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


In [31]:
print(np.arange(10000).reshape(100, 100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


# Basic Operations

In [32]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)
b

array([0, 1, 2, 3])

In [33]:
c = a - b
c

array([20, 29, 38, 47])

In [34]:
b**2

array([0, 1, 4, 9])

In [35]:
10 * np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [36]:
a < 35

array([ True,  True, False, False])

In [37]:
A = np.array([[1, 1],
              [0, 1]])
B = np.array([[2, 0],
              [3, 4]])
A * B     # elementwise product

array([[2, 0],
       [0, 4]])

In [38]:
A @ B 

array([[5, 4],
       [3, 4]])

In [39]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [40]:
rg = np.random.default_rng(1)  # create instance of default random number generator
a = np.ones((2, 3), dtype=int)
b = rg.random((2, 3))
a *= 3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [41]:
b += a
b

array([[3.51182162, 3.9504637 , 3.14415961],
       [3.94864945, 3.31183145, 3.42332645]])

**a += b**  <p> # b is not automatically converted to integer type

In [42]:
a = np.ones(3, dtype=np.int32)
b = np.linspace(0, pi, 3)
b.dtype.name

'float64'

In [43]:
c = a + b
c

array([1.        , 2.57079633, 4.14159265])

In [44]:
c.dtype.name

'float64'

In [45]:
d = np.exp(c * 1j)
d

array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
       -0.54030231-0.84147098j])

In [46]:
d.dtype.name

'complex128'

In [47]:
a = rg.random((2, 3))
a

array([[0.82770259, 0.40919914, 0.54959369],
       [0.02755911, 0.75351311, 0.53814331]])

In [48]:
a.sum()

3.1057109529998157

In [49]:
a.min()

0.027559113243068367

In [50]:
a.max()

0.8277025938204418

In [51]:
b = np.arange(12).reshape(3, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [52]:
b.sum(axis=0)     # sum of each column

array([12, 15, 18, 21])

In [53]:
b.min(axis=1)

array([0, 4, 8])

In [54]:
b.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

# universal functions

In [55]:
B = np.arange(3)
B

array([0, 1, 2])

In [56]:
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [57]:
np.sqrt(B)

array([0.        , 1.        , 1.41421356])

In [58]:
C = np.array([2., -1., 4.])
np.add(B, C)

array([2., 0., 6.])

# Indexing, Slicing and Iterating

In [59]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [60]:
a[2]

8

In [61]:
a[2:5]

array([ 8, 27, 64])

In [62]:
# equivalent to a[0:6:2] = 1000;
# from start to position 6, exclusive, set every 2nd element to 1000
a[:6:2] = 1000
a

array([1000,    1, 1000,   27, 1000,  125,  216,  343,  512,  729])

In [63]:
a[::-1]

array([ 729,  512,  343,  216,  125, 1000,   27, 1000,    1, 1000])

In [64]:
for i in a:
    print(i**(1 / 3.))

9.999999999999998
1.0
9.999999999999998
3.0
9.999999999999998
4.999999999999999
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


In [65]:
def f(x, y):
    return 10 * x + y

In [66]:
b = np.fromfunction(f, (5, 4), dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [67]:
b[2, 3]

23

In [68]:
b[0:5, 1]

array([ 1, 11, 21, 31, 41])

In [69]:
b[:, 1]

array([ 1, 11, 21, 31, 41])

In [70]:
b[1:3, :]

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [71]:
b[-1]   # the last row. Equivalent to b[-1, :]

array([40, 41, 42, 43])

x[1, 2, ...] is equivalent to x[1, 2, :, :, :],

x[..., 3] to x[:, :, :, :, 3] and

x[4, ..., 5, :] to x[4, :, :, 5, :].

In [72]:
c = np.array([[[  0,  1,  2],  # a 3D array (two stacked 2D arrays)
               [ 10, 12, 13]],
              [[100, 101, 102],
               [110, 112, 113]]])

In [73]:
c.shape

(2, 2, 3)

In [74]:
c[1, ...]

array([[100, 101, 102],
       [110, 112, 113]])

In [75]:
c[..., 2]

array([[  2,  13],
       [102, 113]])

In [76]:
for row in b:
    print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [77]:
for element in b.flat:
    print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


# Shape Manipulation

## Changing the shape of an array


In [78]:
a = np.floor(10 * rg.random((3, 4)))

In [79]:
a

array([[3., 7., 3., 4.],
       [1., 4., 2., 2.],
       [7., 2., 4., 9.]])

In [80]:
a.ravel() 

array([3., 7., 3., 4., 1., 4., 2., 2., 7., 2., 4., 9.])

In [81]:
a.reshape(6, 2)

array([[3., 7.],
       [3., 4.],
       [1., 4.],
       [2., 2.],
       [7., 2.],
       [4., 9.]])

In [82]:
a.T

array([[3., 1., 7.],
       [7., 4., 2.],
       [3., 2., 4.],
       [4., 2., 9.]])

In [83]:
a.T.shape

(4, 3)

In [84]:
a.shape

(3, 4)

In [85]:
a.resize((2, 6))

In [86]:
a

array([[3., 7., 3., 4., 1., 4.],
       [2., 2., 7., 2., 4., 9.]])

     reshape返回一个修改的数组 
     resize 修改数组本身

In [87]:
a.reshape(3, -1)  # -1自动计算长度

array([[3., 7., 3., 4.],
       [1., 4., 2., 2.],
       [7., 2., 4., 9.]])

## Stacking together different arrays

In [88]:
a = np.floor(10 * rg.random((2, 2)))

In [89]:
a

array([[9., 7.],
       [5., 2.]])

In [90]:
b = np.floor(10 * rg.random((2, 2)))

In [91]:
b

array([[1., 9.],
       [5., 1.]])

In [92]:
np.vstack((a, b))

array([[9., 7.],
       [5., 2.],
       [1., 9.],
       [5., 1.]])

In [93]:
np.hstack((a, b))

array([[9., 7., 1., 9.],
       [5., 2., 5., 1.]])

In [94]:
from numpy import newaxis

In [95]:
np.column_stack((a, b))

array([[9., 7., 1., 9.],
       [5., 2., 5., 1.]])

In [96]:
a = np.array([4., 2.])
b = np.array([3., 8.])
np.column_stack((a, b))

array([[4., 3.],
       [2., 8.]])

In [97]:
np.hstack((a, b))

array([4., 2., 3., 8.])

In [98]:
a[:, newaxis]

array([[4.],
       [2.]])

In [99]:
np.column_stack((a[:, newaxis], b[:, newaxis]))

array([[4., 3.],
       [2., 8.]])

In [100]:
np.hstack((a[:, newaxis], b[:, newaxis]))

array([[4., 3.],
       [2., 8.]])

In [101]:
np.column_stack is np.hstack

False

In [102]:
np.row_stack is np.vstack

True

In [103]:
np.r_[1:4, 0, 4]

array([1, 2, 3, 0, 4])

## Copies and Views

### No Copy at All

In [104]:
a = np.array([[ 0,  1,  2,  3],
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11]])

In [105]:
b = a 

In [106]:
b is a

True

In [107]:
def f(x):
    print(id(x))


In [108]:
id(a)

139698381824240

In [109]:
f(a)

139698381824240


### View or Shallow Copy

In [110]:
c = a.view()

In [111]:
c is a

False

In [112]:
c.base is a

True

In [113]:
c.flags.owndata

False

In [114]:
c = c.reshape((2, 6))

In [115]:
a.shape

(3, 4)

In [116]:
c[0, 4] = 1234 

In [117]:
a

array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

In [118]:
s = a[:, 1:3]

In [119]:
s[:] = 10

In [120]:
a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])